import { selectOption } from './select-option'
import { expect, test } from '@playwright/test'

test('video preview, precision trim, clip persistence, edit and delete', async ({ page, request }, testInfo) => {
  const errors: string[] = []
  page.on('pageerror', error => errors.push(error.message))
  await page.goto('/')
  await page.getByRole('button', { name: 'Video library' }).click()
  await page.getByRole('button', { name: 'Watch & cut' }).first().click()
  await expect(page.getByRole('heading', { name: 'Cut a new sound' })).toBeVisible()
  await expect(page.getByRole('slider', { name: 'Clip volume' })).toHaveCount(0)
  const start = page.getByTestId('trim-start')
  await expect(start).toBeVisible()
  await expect(page.getByRole('button', { name: 'Preview cut' })).toBeEnabled()
  await page.getByTestId('wave-viewport').evaluate(element => element.scrollIntoView({ block: 'center' }))

  const before = await page.getByLabel('Start time').inputValue()
  if (testInfo.project.name === 'touch') {
    const point = await start.boundingBox()
    const session = await page.context().newCDPSession(page)
    const x = point!.x + point!.width / 2 + 3
    const y = point!.y + point!.height / 2
    await session.send('Input.dispatchTouchEvent', { type: 'touchStart', touchPoints: [{ x, y }] })
    await expect(page.getByText('Precision mode · 4×')).toBeVisible()
    await session.send('Input.dispatchTouchEvent', { type: 'touchMove', touchPoints: [{ x: x + 45, y }] })
    await session.send('Input.dispatchTouchEvent', { type: 'touchEnd', touchPoints: [] })
    await session.detach()
  } else {
    const point = await start.boundingBox()
    await page.mouse.move(point!.x + point!.width / 2 + 2, point!.y + point!.height / 2)
    await page.mouse.down()
    await expect(page.getByText('Precision mode · 4×')).toBeVisible()
    await page.mouse.move(point!.x + point!.width / 2 + 47, point!.y + point!.height / 2)
    await page.mouse.up()
  }
  await expect(page.getByText('Precision mode · 4×')).not.toBeVisible()
  expect(Number(await page.getByLabel('Start time').inputValue())).toBeGreaterThan(Number(before))
  await page.getByLabel('Start time').fill('1')
  await page.getByLabel('End time').fill('2.5')
  await page.getByRole('button', { name: 'Preview cut' }).click()
  await expect(page.locator('video')).toHaveJSProperty('paused', true, { timeout: 10000 })
  const name = `Browser test ${testInfo.project.name} ${Date.now()}`
  await page.getByLabel('Sound name', { exact: true }).fill(name)
  await page.getByLabel('Emoji', { exact: true }).fill('🔊')
  await page.getByRole('button', { name: 'Add to soundboard' }).click()
  await expect(page.getByRole('heading', { name, exact: true })).toBeVisible()
  await expect(page.getByRole('button', { name: `Play ${name} in Discord`, exact: true })).toBeDisabled()
  await page.reload()
  await expect(page.getByRole('heading', { name, exact: true })).toBeVisible()
  const card = page.locator('.sound-card').filter({ has: page.getByRole('heading', { name, exact: true }) })
  await card.getByRole('button', { name: 'Preview', exact: true }).click()
  await expect(card.getByRole('button', { name: 'Stop preview', exact: true })).toBeVisible()
  await expect(card.getByRole('button', { name: 'Stop preview', exact: true }).locator('svg.lucide-headphones')).toBeVisible()
  await page.getByRole('button', { name: `Edit ${name}`, exact: true }).click()
  await expect(page.getByRole('dialog').getByRole('slider', { name: 'Volume', exact: true })).toHaveValue('1')
  await page.getByRole('dialog').getByLabel('Sound name').fill(`${name} edited`)
  await page.getByRole('button', { name: 'Save changes' }).click()
  await expect(page.getByRole('heading', { name: `${name} edited`, exact: true })).toBeVisible()
  await page.getByRole('button', { name: `Edit ${name} edited`, exact: true }).click()
  await page.getByRole('button', { name: 'Delete sound' }).click()
  await expect(page.getByRole('dialog')).toContainText('permanently removes the sound from the soundboard')
  await expect(page.getByRole('dialog')).toContainText('cannot be undone')
  await page.getByRole('dialog').getByRole('button', { name: 'Delete', exact: true }).click()
  await expect(page.getByRole('heading', { name: `${name} edited`, exact: true })).toHaveCount(0)
  expect(errors).toEqual([])
  const response = await request.get('/api/state')
  expect(JSON.stringify(await response.json())).not.toContain('MTUw')
})

test('imports display actionable failure and retry; layout fits viewport', async ({ page }) => {
  await page.goto('/')
  await page.getByRole('button', { name: 'Video library' }).click()
  await page.getByLabel('Video URL').fill('http://127.0.0.1/private-video')
  await page.getByRole('button', { name: 'Import video', exact: true }).click()
  await expect(page.getByText('Local and private network destinations are not allowed.').first()).toBeVisible()
  await expect(page.getByRole('button', { name: 'Retry', exact: true }).first()).toBeEnabled()
  const jobId = await page.locator('.job.failed').first().getAttribute('data-testid')
  await page.getByTestId(jobId!).getByRole('button', { name: 'Dismiss import error' }).click()
  await expect(page.getByTestId(jobId!)).toHaveCount(0)
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= window.innerWidth)).toBeTruthy()
})

test('fast trim stays normal, slow trim zooms, Space starts selection and emoji picker works', async ({ page }, testInfo) => {
  await page.goto('/')
  await page.getByRole('button', { name: 'Video library' }).click()
  await page.getByRole('button', { name: 'Watch & cut' }).first().click()
  const handle = page.getByTestId('trim-start')
  await expect(handle).toBeVisible()
  await page.getByTestId('wave-viewport').evaluate(element => element.scrollIntoView({ block: 'center' }))
  const bounds = await handle.boundingBox()
  let x = bounds!.x + bounds!.width / 2 + 2
  const y = bounds!.y + bounds!.height / 2
  const touch = testInfo.project.name === 'touch' ? await page.context().newCDPSession(page) : null
  if (touch) await touch.send('Input.dispatchTouchEvent', { type: 'touchStart', touchPoints: [{ x, y }] })
  else { await page.mouse.move(x, y); await page.mouse.down() }
  for (let index = 0; index < 3; index++) {
    x += 12
    if (touch) await touch.send('Input.dispatchTouchEvent', { type: 'touchMove', touchPoints: [{ x, y }] })
    else await page.mouse.move(x, y)
  }
  await expect(page.getByText('Precision mode · 4×')).not.toBeVisible()
  await expect(page.getByText('Precision mode · 4×')).toBeVisible()
  x += 50
  if (touch) await touch.send('Input.dispatchTouchEvent', { type: 'touchMove', touchPoints: [{ x, y }] })
  else await page.mouse.move(x, y)
  await expect(page.getByText('Precision mode · 4×')).toBeVisible()
  if (touch) { await touch.send('Input.dispatchTouchEvent', { type: 'touchEnd', touchPoints: [] }); await touch.detach() }
  else await page.mouse.up()
  await expect(page.getByText('Precision mode · 4×')).not.toBeVisible()
  const scroll = page.getByTestId('wave-viewport').locator('[part="scroll"]')
  await expect(scroll).toHaveClass(/noScrollbar/)
  await page.getByLabel('Start time').fill('1')
  await page.getByLabel('End time').fill('5')
  await page.getByRole('heading', { name: 'Cut a new sound' }).click()
  await page.locator('video').evaluate((video: HTMLVideoElement) => { video.currentTime = 7 })
  await page.keyboard.press('Space')
  await expect(page.locator('video')).toHaveJSProperty('paused', false)
  await expect.poll(async () => page.locator('video').evaluate((video: HTMLVideoElement) => video.currentTime)).toBeLessThan(3)
  await page.keyboard.press('Space')
  await expect(page.locator('video')).toHaveJSProperty('paused', true)
  await page.getByRole('button', { name: 'Choose emoji' }).click()
  await page.getByLabel('Search emojis').fill('laugh')
  await page.getByRole('button', { name: '😂 face with tears of joy', exact: true }).click()
  await expect(page.getByLabel('Emoji', { exact: true })).toHaveValue('😂')
  await page.getByLabel('Sound name', { exact: true }).fill('Words')
  await page.keyboard.press('Space')
  await expect(page.getByLabel('Sound name', { exact: true })).toHaveValue('Words ')
  await expect(page.locator('video')).toHaveJSProperty('paused', true)
})
test('caption search filters, synchronized seek and clip extraction', async ({ page }, testInfo) => {
  const errors: string[] = []
  page.on('pageerror', error => errors.push(error.message))
  await page.goto('/')
  await page.getByRole('button', { name: 'Video library' }).click()
  await selectOption(page.getByLabel('Caption language'), 'nl')
  await page.getByLabel('Search captions').fill('wereld')
  await expect(page.locator('.caption-result')).toHaveCount(1)
  await expect(page.locator('.caption-result mark')).toHaveText('wereld')
  await selectOption(page.getByLabel('Caption language'), 'en')
  await expect(page.locator('.caption-result mark')).toHaveText('world')
  await page.getByLabel('Search captions').fill('no matching gibberish')
  await expect(page.getByText('No matching captions.', { exact: false })).toBeVisible()
  await page.getByLabel('Search captions').fill('beautiful world')
  await page.getByRole('button', { name: 'Jump to 0:02: Hello beautiful world' }).click()
  await expect(page.getByRole('heading', { name: 'Cut a new sound' })).toBeVisible()
  await expect.poll(async () => page.locator('video').evaluate((video: HTMLVideoElement) => video.currentTime)).toBeCloseTo(2, 1)
  await expect(page.locator('video')).toHaveJSProperty('paused', true)
  await page.getByLabel('Search captions').fill('mooie wereld')
  await expect(page.locator('.caption-result')).toHaveCount(1)
  await page.getByRole('button', { name: 'Use for clip' }).click()
  await expect(page.getByLabel('Start time')).toHaveValue('2')
  await expect(page.getByLabel('End time')).toHaveValue('4')
  await page.getByRole('button', { name: 'Preview cut' }).click()
  await expect(page.locator('video')).toHaveJSProperty('paused', true, { timeout: 10000 })
  const name = `Caption cut ${testInfo.project.name}`
  await page.getByLabel('Sound name', { exact: true }).fill(name)
  await page.getByRole('button', { name: 'Add to soundboard' }).click()
  await expect(page.getByRole('heading', { name, exact: true })).toBeVisible()
  await expect(page.getByRole('button', { name: `Play ${name} in Discord`, exact: true })).toBeDisabled()
  await page.getByRole('button', { name: `Edit ${name}`, exact: true }).click()
  await page.getByRole('button', { name: 'Delete sound' }).click()
  await expect(page.getByRole('dialog')).toContainText('permanently removes the sound from the soundboard')
  await expect(page.getByRole('dialog')).toContainText('cannot be undone')
  await page.getByRole('dialog').getByRole('button', { name: 'Delete', exact: true }).click()
  expect(errors).toEqual([])
})
test('move selection preserves length and handles fit inside waveform margins', async ({ page }, testInfo) => {
  await page.route('**/api/state*', async route => {
    const response = await route.fetch()
    const state = await response.json()
    state.channels = [{ id: '123', name: 'The voice room', category: 'Hidden category' }]
    state.status.bot_ready = true
    await route.fulfill({ response, json: state })
  })
  await page.goto('/')
  await page.getByLabel('Voice channel').click()
  await expect(page.getByRole('option', { name: 'The voice room', exact: true })).toBeVisible()
  await page.getByRole('option', { name: 'The voice room', exact: true }).press('Escape')
  expect(parseFloat(await page.getByLabel('Voice channel').evaluate(element => getComputedStyle(element).paddingRight))).toBeGreaterThanOrEqual(18)
  await page.getByRole('button', { name: 'Video library' }).click()
  await page.getByRole('button', { name: 'Watch & cut' }).first().click()
  await expect(page.getByTestId('trim-start')).toBeVisible()
  await page.getByLabel('Start time').fill('1')
  await page.getByLabel('End time').fill('3')
  const region = page.getByTestId('selection-region')
  await region.scrollIntoViewIfNeeded()
  const bounds = await region.boundingBox()
  let x = bounds!.x + bounds!.width / 2
  const y = bounds!.y + bounds!.height / 2
  const touch = testInfo.project.name === 'touch' ? await page.context().newCDPSession(page) : null
  if (touch) await touch.send('Input.dispatchTouchEvent', { type: 'touchStart', touchPoints: [{ x, y }] })
  else { await page.mouse.move(x, y); await page.mouse.down() }
  x += 40
  if (touch) await touch.send('Input.dispatchTouchEvent', { type: 'touchMove', touchPoints: [{ x, y }] })
  else await page.mouse.move(x, y)
  await expect.poll(async () => Number(await page.getByLabel('Start time').inputValue())).toBeGreaterThan(1)
  await expect(page.getByText('Precision mode · 4×')).toBeVisible()
  x += 35
  if (touch) await touch.send('Input.dispatchTouchEvent', { type: 'touchMove', touchPoints: [{ x, y }] })
  else await page.mouse.move(x, y)
  await expect(page.getByText('Precision mode · 4×')).toBeVisible()
  if (touch) { await touch.send('Input.dispatchTouchEvent', { type: 'touchEnd', touchPoints: [] }); await touch.detach() }
  else await page.mouse.up()
  await expect(page.getByText('Precision mode · 4×')).not.toBeVisible()
  const start = Number(await page.getByLabel('Start time').inputValue())
  const end = Number(await page.getByLabel('End time').inputValue())
  expect(end - start).toBeCloseTo(2, 5)
  await region.focus()
  for (let index = 0; index < 12; index++) await page.keyboard.press('Shift+ArrowRight')
  await expect(page.getByLabel('Start time')).toHaveValue('8')
  await expect(page.getByLabel('End time')).toHaveValue('10')
  for (let index = 0; index < 12; index++) await page.keyboard.press('Shift+ArrowLeft')
  await expect(page.getByLabel('Start time')).toHaveValue('0')
  await expect(page.getByLabel('End time')).toHaveValue('2')
  await page.getByLabel('End time').fill('10')
  const frame = await page.locator('.wave-frame').boundingBox()
  const left = await page.getByTestId('trim-start').boundingBox()
  const right = await page.getByTestId('trim-end').boundingBox()
  expect(left!.x).toBeGreaterThan(frame!.x)
  expect(right!.x + right!.width).toBeLessThan(frame!.x + frame!.width)
})
test('tag chips reuse and create tags, longer names and comfortable emoji spacing', async ({ page, request }) => {
  const seed = await request.post('/api/clips', { data: { source_id: 'fixture', start: 1, end: 2, name: 'Tag seed', tags: ['existing'] } })
  expect(seed.ok()).toBeTruthy()
  const seedId = (await seed.json()).id
  await page.goto('/')
  await page.getByRole('button', { name: 'Video library' }).click()
  await page.getByRole('button', { name: 'Watch & cut' }).first().click()
  await expect(page.getByRole('button', { name: 'Preview cut' })).toBeEnabled()
  await expect(page.locator('video')).toHaveJSProperty('disablePictureInPicture', true)
  await expect(page.getByLabel('Sound name', { exact: true })).toHaveAttribute('maxlength', '255')
  const emoji = await page.getByLabel('Emoji', { exact: true }).boundingBox()
  const picker = await page.getByRole('button', { name: 'Choose emoji' }).boundingBox()
  expect(picker!.x - (emoji!.x + emoji!.width)).toBeGreaterThanOrEqual(9)
  await page.getByLabel('Tags', { exact: true }).fill('exis')
  await page.getByRole('group', { name: 'Tag suggestions' }).getByRole('button', { name: 'existing', exact: true }).click()
  await expect(page.getByRole('button', { name: 'Remove tag existing' })).toBeVisible()
  await page.getByLabel('Tags', { exact: true }).fill('new tag')
  await page.getByLabel('Tags', { exact: true }).press('Enter')
  await expect(page.getByRole('button', { name: 'Remove tag new tag' })).toBeVisible()
  await page.getByRole('button', { name: 'Remove tag existing' }).click()
  await expect(page.getByRole('button', { name: 'Remove tag existing' })).toHaveCount(0)
  const name = 'Long sound '.padEnd(255, 'x')
  await page.getByLabel('Sound name', { exact: true }).fill(name)
  const saved = page.waitForResponse(response => response.url().endsWith('/api/clips') && response.request().method() === 'POST')
  await page.getByRole('button', { name: 'Add to soundboard' }).click()
  const clipId = (await (await saved).json()).id
  await expect(page.getByRole('heading', { name, exact: true })).toBeVisible()
  await page.getByRole('button', { name: `Edit ${name}`, exact: true }).click()
  await expect(page.getByRole('button', { name: 'Remove tag new tag' })).toBeVisible()
  await page.getByLabel('Tags', { exact: true }).fill('existing')
  await page.getByRole('group', { name: 'Tag suggestions' }).getByRole('button', { name: 'existing', exact: true }).click()
  await page.getByRole('button', { name: 'Save changes' }).click()
  const state = await (await request.get('/api/state')).json()
  expect(state.clips.find((clip: { id: string }) => clip.id === clipId).tags).toEqual(['new tag', 'existing'])
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= window.innerWidth)).toBeTruthy()
  await request.delete(`/api/clips/${clipId}`)
  await request.delete(`/api/clips/${seedId}`)
})
test('channel links start a batch and show progress with pause and resume', async ({ page }) => {
  let status = ''
  await page.route('**/api/state*', async route => {
    const response = await route.fetch()
    const state = await response.json()
    state.channel_imports = status ? [{ id: 'batch', title: 'Kud channel', url: 'https://www.youtube.com/@KudNL/videos', status, error: null, total: 5, counts: { complete: 1, skipped: 1, queued: 3 }, current: null }] : []
    await route.fulfill({ response, json: state })
  })
  await page.route('**/api/channel-imports', async route => {
    expect(route.request().postDataJSON().url).toBe('https://www.youtube.com/@KudNL/videos')
    status = 'running'
    await route.fulfill({ status: 202, json: { batch_id: 'batch' } })
  })
  await page.route('**/api/channel-imports/batch/pause', async route => { status = 'paused'; await route.fulfill({ json: { ok: true } }) })
  await page.route('**/api/channel-imports/batch/resume', async route => { status = 'running'; await route.fulfill({ json: { ok: true } }) })
  await page.goto('/')
  await page.getByRole('button', { name: 'Video library' }).click()
  await page.getByLabel('Video URL').fill('https://www.youtube.com/@KudNL/videos')
  await page.getByRole('button', { name: 'Import channel', exact: true }).click()
  const batch = page.getByRole('region', { name: 'Channel imports' })
  await expect(batch.getByText('Kud channel')).toBeVisible()
  await expect(batch.getByText('running · 1 imported · 1 already saved · 0 failed · 3 queued')).toBeVisible()
  await expect(batch.getByRole('progressbar')).toHaveAttribute('value', '2')
  await batch.getByRole('button', { name: 'Pause channel' }).click()
  await expect(batch.getByRole('button', { name: 'Resume channel' })).toBeEnabled()
  await batch.getByRole('button', { name: 'Resume channel' }).click()
  await expect(batch.getByRole('button', { name: 'Pause channel' })).toBeVisible()
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= window.innerWidth)).toBeTruthy()
})
test('successful channel notices clear on reload while unfinished and failed batches remain', async ({ page }) => {
  let completed = false
  await page.route('**/api/state*', async route => {
    const response = await route.fetch()
    const state = await response.json()
    const batch = { url: 'https://www.youtube.com/@KudNL/videos', error: null, total: 5, current: null }
    state.channel_imports = [
      { ...batch, id: 'old', title: 'Previous import', status: 'complete', counts: { complete: 5 } },
      { ...batch, id: 'skipped', title: 'Already saved import', status: 'complete', counts: { skipped: 5 } },
      { ...batch, id: 'current', title: 'Current import', status: completed ? 'complete' : 'running', counts: completed ? { complete: 5 } : { queued: 5 } },
      { ...batch, id: 'paused', title: 'Paused import', status: 'paused', counts: { queued: 5 } },
      { ...batch, id: 'failed', title: 'Failed import', status: 'complete', counts: { complete: 4, failed: 1 } },
      { ...batch, id: 'error', title: 'Import with error', status: 'failed', error: 'Channel unavailable', counts: {} },
    ]
    await route.fulfill({ response, json: state })
  })
  await page.route('**/api/channel-imports/current/pause', async route => {
    completed = true
    await route.fulfill({ json: { ok: true } })
  })
  await page.goto('/videos')
  const notices = page.getByRole('region', { name: 'Channel imports' })
  await expect(notices.getByText('Previous import', { exact: true })).toHaveCount(0)
  await expect(notices.getByText('Already saved import', { exact: true })).toHaveCount(0)
  await notices.getByRole('button', { name: 'Pause channel' }).click()
  await expect(notices.getByText('complete · 5 imported · 0 already saved · 0 failed · 0 queued')).toBeVisible()
  await page.getByRole('button', { name: 'Soundboard', exact: false }).click()
  await page.getByRole('button', { name: 'Video library', exact: false }).click()
  await expect(notices.getByText('Current import', { exact: true })).toBeVisible()
  await page.reload()
  await expect(notices.getByText('Paused import', { exact: true })).toBeVisible()
  await expect(notices.getByText('Failed import', { exact: true })).toBeVisible()
  await expect(notices.getByText('Channel unavailable', { exact: true })).toBeVisible()
  await expect(notices.getByText('Current import', { exact: true })).toHaveCount(0)
  await expect(notices.getByText('Previous import', { exact: true })).toHaveCount(0)
})

test('page URLs survive reload and history, editor URLs include video ID', async ({ page }) => {
  await page.goto('/')
  await expect(page).toHaveURL(/\/soundboard$/)
  await page.getByRole('button', { name: 'Video library' }).click()
  await expect(page).toHaveURL(/\/videos$/)
  await page.reload()
  await expect(page.getByRole('heading', { name: 'Video library.' })).toBeVisible()
  await page.getByRole('button', { name: 'Watch & cut' }).first().click()
  await expect(page).toHaveURL(/\/videos\/fixture\/cut$/)
  await page.reload()
  await expect(page.getByRole('heading', { name: 'Cut a new sound' })).toBeVisible()
  await expect(page.getByRole('button', { name: 'Preview cut' })).toBeEnabled()
  await page.goBack()
  await expect(page).toHaveURL(/\/videos$/)
  await expect(page.getByRole('button', { name: 'Watch & cut' }).first()).toBeVisible()
  await page.goForward()
  await expect(page.getByRole('heading', { name: 'Cut a new sound' })).toBeVisible()
  await page.goto('/videos/fixture/cut?t=2')
  await expect(page.getByRole('button', { name: 'Preview cut' })).toBeEnabled()
  await expect.poll(async () => page.locator('video').evaluate((video: HTMLVideoElement) => video.currentTime)).toBeCloseTo(2, 1)
  await page.reload()
  await expect.poll(async () => page.locator('video').evaluate((video: HTMLVideoElement) => video.currentTime)).toBeCloseTo(2, 1)
  await page.goto('/videos/missing/cut')
  await expect(page.getByRole('heading', { name: 'Video not found' })).toBeVisible()
  await page.getByRole('button', { name: 'Back to library' }).click()
  await expect(page).toHaveURL(/\/videos$/)
  await page.getByRole('button', { name: 'Soundboard' }).click()
  await page.reload()
  await expect(page).toHaveURL(/\/soundboard$/)
  await expect(page.getByRole('heading', { name: 'Your soundboard.' })).toBeVisible()
})
